import type { Metadata } from "next";
import {
  Google_Sans,
  Google_Sans_Code,
  Google_Sans_Flex,
} from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navigation/navbar";

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

const googleCode = Google_Sans_Code({
  variable: "--font-google-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`mx-auto max-w-6xl ${googleSans.variable} ${googleCode.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
